name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: echo "Demo update" >> README.md
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update README"
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
